spring.application.name=Exemplo2

#URl Conexão com o Banco
spring.datasource.url=jdbc:h2:mem:bancoteste

#DEFINIR O USUARIO PADRAO (banco):
spring.datasource.username=sa


#DEFINIR A SENHA DO USUARIO
spring.datasource.password=

#habilita o console do h2
spring.h2.console.enable=true

#define a url do console
spring.h2.console.path=/h2-console


#para o h2 funcionar via codespace
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework

#configura o JPA para a estrutura do banco
